### ISSUE TITLE
Expression statements with comparison operator results in Unhandled exception

### ISSUE THREAD

**Issue by wixette** [SeedV/SeedLang#134]
```
dotnet run --project src/SeedLang.Shell 
SeedLang.Shell 0.2.0-preview20220222133854
Copyright 2021-2022 The SeedV Lab.

>>> 1 == 1
---------- Source ----------
1 == 1

---------- Run ----------
Unhandled exception. System.InvalidOperationException: Stack empty.
   at System.Collections.Generic.Stack`1.ThrowForEmptyStack()
   at System.Collections.Generic.Stack`1.Peek()
   at SeedLang.Interpreter.NestedJumpStack.get_FalseJumps() in /Users/ygwang/src/SeedLang/csharp/src/SeedLang/Interpreter/NestedJumpStack.cs:line 30
   at SeedLang.Interpreter.Compiler.VisitSingleComparison(Expression left, ComparisonOperator op, Expression right, Range range) in /Users/ygwang/src/SeedLang/csharp/src/SeedLang/Interpreter/Compiler.cs:line 363
   at SeedLang.Interpreter.Compiler.Visit(ComparisonExpression comparison) in /Users/ygwang/src/SeedLang/csharp/src/SeedLang/Interpreter/Compiler.cs:line 93
   at SeedLang.Ast.AstWalker.Visit(Expression expression) in /Users/ygwang/src/SeedLang/csharp/src/SeedLang/Ast/AstWalker.cs:line 44
   at SeedLang.Interpreter.Compiler.Visit(ExpressionStatement expr) in /Users/ygwang/src/SeedLang/csharp/src/SeedLang/Interpreter/Compiler.cs:line 209
   at SeedLang.Ast.AstWalker.Visit(Statement statement) in /Users/ygwang/src/SeedLang/csharp/src/SeedLang/Ast/AstWalker.cs:line 92
   at SeedLang.Ast.AstWalker.Visit(AstNode node) in /Users/ygwang/src/SeedLang/csharp/src/SeedLang/Ast/AstWalker.cs:line 27
   at SeedLang.Interpreter.Compiler.Compile(AstNode node, GlobalEnvironment env) in /Users/ygwang/src/SeedLang/csharp/src/SeedLang/Interpreter/Compiler.cs:line 46
   at SeedLang.Runtime.Executor.Run(String source, String module, SeedXLanguage language, RunType runType, DiagnosticCollection collection) in /Users/ygwang/src/SeedLang/csharp/src/SeedLang/Runtime/Executor.cs:line 88
   at SeedLang.Shell.Repl.Execute() in /Users/ygwang/src/SeedLang/csharp/src/SeedLang.Shell/Repl.cs:line 49
   at SeedLang.Shell.Program.Run(Options options) in /Users/ygwang/src/SeedLang/csharp/src/SeedLang.Shell/Program.cs:line 65
   at SeedLang.Shell.Program.<>c__DisplayClass1_0.<Main>b__3(Options options) in /Users/ygwang/src/SeedLang/csharp/src/SeedLang.Shell/Program.cs:line 54
   at CommandLine.ParserResultExtensions.WithParsed[T](ParserResult`1 result, Action`1 action)
   at SeedLang.Shell.Program.Main(String[] args) in /Users/ygwang/src/SeedLang/csharp/src/SeedLang.Shell/Program.cs:line 50
```

Similar code that generates the same exception:

```
5 > 3
a = 5 > 3
a <= b
```

**Comment by codingpotato** [comment]
Comparison and logic assignment and evaluation haven't been implemented in SeedVM, will consider it later.
